# This file configures your Netlify deployment.

[build]
  functions = "functions" # Specifies the directory for serverless functions.

[[redirects]]
  from = "/api/*" # Any request starting with /api/...
  to = "/.netlify/functions/api/:splat" # ...will be sent to our api.js function.
  status = 200 # This makes it act as a proxy.